ANSWER_LETTERS = "ABCD"
NUM_OPTIONS = 4

SHEET_TYPE_CIRCLE = "circle"
SHEET_TYPE_RECT = "rect"
SHEET_TYPE_AUTO = "auto"

BUBBLE_MIN_SIZE = 10
BUBBLE_AR_MIN = 0.7
BUBBLE_AR_MAX = 1.4
BUBBLE_SIZE_MULTIPLIER_LOW = 0.6
BUBBLE_SIZE_MULTIPLIER_HIGH = 1.5

RECT_MIN_SIZE = 8
RECT_AR_MIN = 0.5
RECT_AR_MAX = 2.5
RECT_SIZE_MULTIPLIER_LOW = 0.5
RECT_SIZE_MULTIPLIER_HIGH = 1.8
RECT_BRACKET_MIN_W = 4
RECT_BRACKET_MIN_H = 10
RECT_BRACKET_AR_MAX = 0.7
RECT_BRACKET_FILL_MIN = 0.2
RECT_BRACKET_FILL_MAX = 0.7
RECT_BRACKET_Y_TOL = 8
RECT_BRACKET_GAP_MIN = 5
RECT_BRACKET_GAP_MAX = 80
RECT_SOLID_FILL_MIN = 0.75
RECT_RECT_PAD_X = 2
RECT_RECT_PAD_Y = 1
RECT_INNER_FILL_MIN = 0.02
RECT_INNER_PAD_RATIO_X = 0.12
RECT_INNER_PAD_RATIO_Y = 0.15

MORPH_KERNEL_SIZE = 3
COL_GAP_MULTIPLIER = 3

FILL_RATIO_THRESHOLD = 1.3
FILL_MIN_DIFF = 50
BUBBLE_RADIUS_RATIO = 0.45
RECT_PADDING = 2

CANNY_LOW = 75
CANNY_HIGH = 200
GAUSSIAN_KERNEL = (5, 5)

DRAW_COLOR_STUDENT = (255, 0, 0)
DRAW_COLOR_CORRECT = (0, 255, 0)
DRAW_COLOR_WRONG = (0, 0, 255)
DRAW_THICKNESS_STUDENT = 2
DRAW_THICKNESS_ANSWER = 3

DISPLAY_MAX_WIDTH = 1000
DISPLAY_MAX_HEIGHT = 700
