ANSWER_LETTERS = "ABCD"
NUM_OPTIONS = 4

BUBBLE_MIN_SIZE = 10
BUBBLE_AR_MIN = 0.7
BUBBLE_AR_MAX = 1.4
BUBBLE_SIZE_MULTIPLIER_LOW = 0.6
BUBBLE_SIZE_MULTIPLIER_HIGH = 1.5

MORPH_KERNEL_SIZE = 3
COL_GAP_MULTIPLIER = 3

FILL_RATIO_THRESHOLD = 1.3
FILL_MIN_DIFF = 50
BUBBLE_RADIUS_RATIO = 0.45

CANNY_LOW = 75
CANNY_HIGH = 200
GAUSSIAN_KERNEL = (5, 5)

DRAW_COLOR_STUDENT = (255, 0, 0)
DRAW_COLOR_CORRECT = (0, 255, 0)
DRAW_COLOR_WRONG = (0, 0, 255)
DRAW_THICKNESS_STUDENT = 2
DRAW_THICKNESS_ANSWER = 3
